name: Build against eic-shell

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          # install this repo
          CC=gcc CXX=g++ cmake -B build -S .
          cmake --build build -- install
    - uses: actions/upload-artifact@v3
      with:
        name: build-gcc-eic-shell
        path: |
          .
          !src/
        if-no-files-found: error

  build-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          # install this repo
          CC=clang CXX=clang++ cmake -B build -S .
          cmake --build build -- install
    - uses: actions/upload-artifact@v3
      with:
        name: build-clang-eic-shell
        path: |
          .
          !src/
        if-no-files-found: error

  dump-flags:
    runs-on: ubuntu-latest
    needs: build-gcc
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build-gcc-eic-shell
        path: install/
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        network_types: "none"
        #setup: install/bin/setup.sh
        run: |
            echo "ls install"
            ls install
            echo "ls install/bin"
            ls install/bin
            echo "run eicrecon -c"
            eicrecon -c


