name: Build against eic-shell!

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/epic-nightly/setup.sh
        run: |
          # install this repo
          cmake -B build -S . \
            -DDETECTOR_LIBS_EPIC=/opt/detector/epic-nightly/lib/libepic.so \
            -DDETECTOR_LIBS_IP6=/opt/detector/epic-nightly/lib/libip6.so
          cmake --build build -- install
    - uses: actions/upload-artifact@v3
      with:
        name: build-eic-shell-epic-nightly
        path: |
          .
          !src/
        if-no-files-found: error
